import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { registerSW } from 'virtual:pwa-register'
import './index.css'
import App from './App'
import { categoryService } from '@/services/categoryService'

// Register the Workbox service worker (generated by vite-plugin-pwa at build time)
// autoUpdate: new SW activates after the next page load — no prompt required
registerSW({ immediate: false })

// Seed default categories on every startup (idempotent — uses bulkPut by id)
categoryService.seedDefaults().catch(console.error)

const root = document.getElementById('root')
if (!root) throw new Error('Root element not found')

createRoot(root).render(
  <StrictMode>
    <App />
  </StrictMode>
)
